name: docker-manual-triggered-test

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Enter tag name for test/dev image'
        default: 'test'

jobs:
  gcr-dockerhub-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Show Runners environment (debug)
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 120
          command: |
            export
      - name: Build Docker image and tag
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          command: |
            docker build \
              --tag ${{ github.repository }}:${{ github.event.inputs.tags }} \
              --tag ghcr.io/${{ github.repository }}:${{ github.event.inputs.tags }} \
              .
      - name: TEST Create container and run tests
        shell: bash
        run: |
          host_port="9999"
          container_port="8080"
          retry_count=30
          docker run -d --rm --net='bridge' -v /tmp/config:/config -v /tmp/data:/data -v /tmp/media:/media -p "${host_port}:${container_port}" ghcr.io/${{ github.repository }}:${{ github.event.inputs.tags }}
          docker ps
          until lsof -i:${host_port}; do
            retry_count=$((retry_count-1))
            if [ "${retry_count}" -eq "0" ]; then
              echo "Test failed, showing logs..."
              cat /tmp/config/supervisord.log
              exit 1
            fi
            sleep 1s
          done
      - name: Push Docker image to Docker Hub
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 30
          max_attempts: 3
          retry_wait_seconds: 120
          command: |
            docker push ${{ github.repository }}:${{ github.event.inputs.tags }}
      - name: Push Docker image to GitHub Container Registry (GHCR)
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 30
          max_attempts: 3
          retry_wait_seconds: 120
          command: |
            docker push ghcr.io/${{ github.repository }}:${{ github.event.inputs.tags }}